# Generated by Django 4.2.30 on 2026-08-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrequest',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when FI data was last fetched & ingested', null=True),
        ),
    ]
