# Generated by Django 4.2.30 on 2026-07-31 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('ALLOCATION', 'Allocation'), ('AUTO_TRANSFER', 'Auto Transfer / Smart Cover'), ('ADJUSTMENT', 'Manual Adjustment')], default='EXPENSE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('merchant', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('receipt_tag', models.CharField(blank=True, max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance threshold that triggers transfer', max_digits=12)),
                ('transfer_type', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('COVER_DEFICIT', 'Cover Full Deficit')], default='COVER_DEFICIT', max_length=20)),
                ('transfer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_transfers_per_month', models.IntegerField(default=5)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(help_text='Category protected by this rule', on_delete=django.db.models.deletion.CASCADE, related_name='overflow_rules', to='categories.category')),
                ('source_category', models.ForeignKey(help_text='Source category (e.g. Savings) supplying funds', on_delete=django.db.models.deletion.CASCADE, related_name='source_overflow_rules', to='categories.category')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutoTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='categories.category')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='transactions.overflowrule')),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_transfer_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
