# Generated by Django 4.2.30 on 2026-07-31 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual Entry'), ('AUTO_DETECTED', 'Auto-Detected'), ('USER_CORRECTED', 'User Corrected')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_transaction_ref', models.CharField(help_text='Unique transaction reference for de-duplication', max_length=100, unique=True)),
                ('raw_narration', models.TextField()),
                ('normalized_merchant', models.CharField(db_index=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=10)),
                ('date', models.DateField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('AUTO_MATCHED', 'Auto Matched'), ('NEEDS_REVIEW', 'Needs Review'), ('CONFIRMED', 'Confirmed'), ('IGNORED', 'Ignored')], default='NEEDS_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction_source', to='transactions.transaction')),
                ('matched_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_matches', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_transactions', to='transactions.banktransaction'),
        ),
        migrations.CreateModel(
            name='MerchantCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_pattern', models.CharField(db_index=True, help_text='Uppercase merchant key e.g. SWIGGY', max_length=150)),
                ('match_count', models.IntegerField(default=1)),
                ('last_confirmed_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('SYSTEM_DEFAULT', 'System Default'), ('USER_CONFIRMED', 'User Confirmed')], default='USER_CONFIRMED', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_mappings', to='categories.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_confirmed_at'],
                'unique_together': {('user', 'merchant_pattern')},
            },
        ),
    ]
