# Generated by Django 4.2.30 on 2026-07-31 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_sync', '0001_initial'),
        ('transactions', '0002_transaction_source_banktransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='consent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='bank_sync.consentrequest'),
        ),
    ]
